package com.mycompany.programacaodesktop.view;


import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author igork
 */
public final class JogoDaSorte extends javax.swing.JFrame {
    
    int numero = 0;
    int tentativas = 0;
    /**
     * Creates new form JogoDaSorte
     */
    public JogoDaSorte() {
        
        initComponents();
        resetarJogo();
        sorteia();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAdivinha = new javax.swing.JTextArea();
        jbEnviar = new javax.swing.JButton();
        jlCima = new javax.swing.JLabel();
        jlBaixo = new javax.swing.JLabel();
        jlTentativas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jtAdivinha.setColumns(20);
        jtAdivinha.setRows(5);
        jtAdivinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAdivinhaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtAdivinha);

        jbEnviar.setText("Enviar");
        jbEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEnviarMouseClicked(evt);
            }
        });
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jlCima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCima.setText("JOGO DA SORTE");

        jlBaixo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBaixo.setText("DIGITE UM NÚMERO PARA TENTAR A SORTE");

        jlTentativas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlTentativas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlBaixo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(jbEnviar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 238, Short.MAX_VALUE))
                    .addComponent(jlCima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlCima)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jbEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlBaixo)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tentativas(){
        tentativas++;
        jlTentativas.setText("Você já realizou "+tentativas+" tentativas");
    }
    
    public int sorteia(){
        Random random = new Random();
        numero = random.nextInt(11);
        
        return numero;
    }
    
    private void limparCampo(){
        jtAdivinha.setText("");
    }
    
    
    private void resetarJogo(){
        jlCima.setText("JOGO DA SORTE");
        jlBaixo.setText("DIGITE UM NÚMERO PARA TENTAR A SORTE");
        tentativas = 0;
        limparCampo();
    }
    
    private void ganhouJogo(){
        JOptionPane.showMessageDialog(this, "Parabens voce ganhou o jogo");
        resetarJogo();
    }
    private void verificarAdivinha(int escolha, int numero){
        if (escolha == numero) {
                ganhouJogo();
            } else if (escolha > numero) {
                jlBaixo.setText("DIGITE OUTRO NÚMERO PARA TENTAR A SORTE");
                jlCima.setText("O NUMERO ESCOLHIDO É MAIOR QUE O NUMERO DA SORTE");
            } else {
                jlBaixo.setText("DIGITE OUTRO NÚMERO PARA TENTAR A SORTE");
                jlCima.setText("O NUMERO ESCOLHIDO É MENOR QUE O NUMERO DA SORTE");
            } 
        limparCampo();
    }
    
    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEnviarActionPerformed

    private void jbEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEnviarMouseClicked
        // TODO add your handling code here
        
        int escolha = Integer.parseInt(jtAdivinha.getText());
        
        verificarAdivinha(escolha, numero);
    }//GEN-LAST:event_jbEnviarMouseClicked

    private void jtAdivinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAdivinhaKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            int escolha = Integer.parseInt(jtAdivinha.getText());
            verificarAdivinha(escolha, numero);
            limparCampo();
            tentativas();
        }

    }//GEN-LAST:event_jtAdivinhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JogoDaSorte().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JLabel jlBaixo;
    private javax.swing.JLabel jlCima;
    private javax.swing.JLabel jlTentativas;
    private javax.swing.JTextArea jtAdivinha;
    // End of variables declaration//GEN-END:variables
}
